spring.application.name=streaming

# SQL Server database connection configuration
spring.datasource.url=jdbc:mysql://mysql-3aa2a82e-duongxyz-3604.l.aivencloud.com:12545/defaultdb?useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 1. COMPLETELY DISABLE background scanning and execution of the data.sql file
spring.sql.init.mode=never

# 2. Clean up old configs (The spring.jpa.defer-datasource-initialization line has been removed)

# 3. Allow Hibernate to automatically update the table structures based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

